In [1]:
#old way to pull off strips
#     while not isEmpty(tabList):
#        #print(tabList, steps)
#         corner = upperRightNotEmpty(tabList)
#         i = corner[0]
#         j = corner[1]
#         goodPath = True
#         while goodPath:
#             if isInBounds(tabList,i, j-1) and tabList[i][j] == tabList[i][j-1]:
#                     tabList[i][j] -= 1
#                     j = j - 1
#             else:
#                 if not isInBounds(tabList, i+1, j):
#                     tabList[i][j] -= 1
#                     goodPath = False
#                     steps += 1
#                 else:
#                     tabList[i][j] -= 1
#                     i = i + 1

#methods
def isEmpty(tab):
    for i in range(len(tab)):
        for j in range(len(tab[i])-1,-1,-1):
            if tab[i][j] > 0:
                return False
    return True

def upperRightNotEmpty(tab):
    for i in range(len(tab)):
        for j in range(len(tab[i])-1,-1,-1):
            if tab[i][j] > 0:
                return [i,j]
    return [0,0]

def isInBounds(tab, i, j):
    if i >= 0 and j >= 0 and i < len(tab) and j < len(tab[i]):
        return True
    else:
        return False
def setup(tab):
    tabList = list()
    for i in range(len(tab)):
        rowList = list()
        for j in range(len(tab[i])):
            rowList.append(tab[i][j] - (i+1))
        tabList.append(rowList)
    return tabList

def fitsIn(this, that): #returns true if this "fits in" that - assume they have the same shape and check box-by-box
    for i in range(len(this)):
        for j in range(len(this[i])):
            if this[i][j] > that[i][j]:
                return False
    return True

def maxCorner(maxTab):
    best = 0
    for i in range(len(maxTab)):
        best = max(best, maxTab[i][len(maxTab[i])-1] + (i + 1))
    return best

def maxRemove(maxTab):
    runSum = 0
    for i in range(len(maxTab)):
        runSum += maxTab[i][-1]
    return runSum
def posSet(shapeHelp):
    shape = list()
    for x in shapeHelp:
        shape.append(x)
    shape.append(0)
    returnSet = set()
    for k in range(len(shape)-1):
        if (shape[k] != shape[k+1]):
            i = k
            j = shape[i]-1
            while(i >= 0 and j >= 0):
                returnSet.add(tuple([i,j]))
                i = i - 1
                j = j - 1
    i = len(shape)-1
    j = shape[i]
    return returnSet
def negSet(shape):
    returnSet = set()
    for k in range(len(shape)):
        if(k != 0):
            if (shape[k] != shape[k-1]):
                i = k-1
                j = shape[k]-1
                while(i >= 0 and j >= 0):
                    returnSet.add(tuple([i,j]))
                    i = i - 1
                    j = j - 1
    i = len(shape)-1
    j = shape[i]
    return returnSet
def sumOfEntries(lam):
    ans = 0
    for row in lam:
        for x in row:
            ans += x
    return ans
print("technologic")

technologic


In [9]:
#maxEntry implementation
tabShape = [5,5,3,3,1]
maxEntry = len(tabShape) + 1
pos = posSet(tabShape)
neg = negSet(tabShape)
stepCounts = [0]*(len(tabShape)*(maxEntry-1)+1)
secondStepCounts = [0]*(len(tabShape)*(maxEntry-1)+1)
num = 0
for tab in SemistandardTableaux(tabShape, max_entry = maxEntry):
    steps = 0
    tabList = setup(tab)
    for point in pos:
        i = point[0]
        j = point[1]
        steps += tabList[i][j]
    for point in neg:
        i = point[0]
        j = point[1]
        steps -= tabList[i][j]
    stepCounts[steps] += 1   
print(stepCounts)
runSum = 0
for x in stepCounts:
    runSum += x
print(runSum)
R.<t> = PolynomialRing(ZZ)
p = 0
for i in range(len(stepCounts)):
    p = p + stepCounts[i]*t^i
print(p)
print(p.factor())

[1, 17, 138, 614, 1825, 3945, 6060, 6060, 3945, 1825, 614, 138, 17, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
25200
t^13 + 17*t^12 + 138*t^11 + 614*t^10 + 1825*t^9 + 3945*t^8 + 6060*t^7 + 6060*t^6 + 3945*t^5 + 1825*t^4 + 614*t^3 + 138*t^2 + 17*t + 1
(t + 1) * (t^12 + 16*t^11 + 122*t^10 + 492*t^9 + 1333*t^8 + 2612*t^7 + 3448*t^6 + 2612*t^5 + 1333*t^4 + 492*t^3 + 122*t^2 + 16*t + 1)


In [32]:
#maxTab implementation
tabShape = [3]
maxTab = [[1,2,3]]
pos = posSet(tabShape)
neg = negSet(tabShape)
#print(maxCorner(maxTab))
stepCounts = [0]*(maxRemove(maxTab)+1)
badCount = 0
for tab in SemistandardTableaux(tabShape, max_entry = maxCorner(maxTab)):
    steps = 0
    tabList = setup(tab)
    #print(tab)
    if(fitsIn(tabList, maxTab)):
        for point in pos:
            i = point[0]
            j = point[1]
            steps += tabList[i][j]
        for point in neg:
            i = point[0]
            j = point[1]
            steps -= tabList[i][j]
        stepCounts[steps] += 1
        #print(tabList, steps)
        #print()
print(stepCounts)
runSum = 0
for x in stepCounts:
    runSum += x
print(runSum)
R.<t> = PolynomialRing(ZZ)
p = 0
for i in range(len(stepCounts)):
    p = p + stepCounts[i]*t^i
print(p)
print(p.factor())

[1, 3, 5, 5]
14
5*t^3 + 5*t^2 + 3*t + 1
5*t^3 + 5*t^2 + 3*t + 1


In [5]:
#crazy nQueens type recursive solution to making fdiagrams
def fDiagramBuilder(previous, i, j, ans):
    hookSum = 0
    for a in range(i):
        hookSum += previous[a][j]
    for b in range(j):
        hookSum += previous[i][b]
    col = j + 1
    maxPick = col - hookSum
    for k in range(maxPick + 1):
        tempNext = list()
        for a in range(len(previous)):
            tempRow = list()
            for b in range(len(previous[a])):
                tempRow.append(previous[a][b])
            tempNext.append(tempRow)
        tempNext[i][j] = k
        if isInBounds(previous, i, j+1):
            fDiagramBuilder(tempNext,i,j+1, ans)
        else:
            if isInBounds(previous,i+1,0):
                fDiagramBuilder(tempNext,i+1,0, ans)
            else:
                temp = list()
                for m in range(len(tempNext)):
                    temp.append(tuple(tempNext[m]))
                if sumOfEntries(temp) == 14:
                    ans.add(tuple(temp))
def maxPathLength(lam):
    startRow = 0
    startCol = len(lam[0]) - 1
    ans = list()
    for i in range(len(lam)):
        ans.append([-1] * len(lam[i]))
    sumAt(lam,startRow,startCol,ans)
    return ans
def sumAt(lam,i,j,ans):
    if i >= len(lam) or j < 0:
        return 0
    elif ans[i][j] != -1:
        return ans[i][j]
    else:
        ans[i][j] = lam[i][j] + max(sumAt(lam,i + 1,j,ans),sumAt(lam,i,j-1,ans))
        return ans[i][j]

In [5]:
n = 7
tabShape = list()
for k in range(n,0,-1):
    tabShape.append(k)
minTab = list()
for x in tabShape:
    minTab.append([0]*x)
distribution = [0]*Integer(((n+1)*(n)/2 + 1))
correct = 0
bad = 0
ans = set()
fDiagramBuilder(minTab, 0, 0, ans)
for fDiag in ans:
    HGdiagram = WeakReversePlanePartition(fDiag)
    #tab = HGdiagram.hillman_grassl()
    goodDiagram = True
    for i in range(len(HGdiagram)):
        j = len(HGdiagram[i])
        checker = list()
        for a in range(i+1):
            checker.append([0]*j)
        for a in range(i+1):
            for b in range(j):
                checker[a][b] = HGdiagram[a][b]
        if maxPathLength(checker)[0][-1] > j:
            goodDiagram = False
    if goodDiagram:
        #couldBeGood = True
        sums = 0
#         for i in range(len(tab)):
#             for j in range(len(tab[i])):
#                 if tab[i][j] > j+1:
#                     couldBeGood = False
#         if couldBeGood:
        for i in range(len(HGdiagram)):
            for j in range(len(HGdiagram[i])):
                sums += HGdiagram[i][j]
        correct +=1
        distribution[sums] += 1
#         else:
#             bad += 1
print(pow(2,Integer((n+1)*(n)/2)), correct, bad)
print(distribution)

KeyboardInterrupt: 

In [9]:
p = Polyhedron(ieqs = [[0,1,0,0,0,0,0],[0,0,1,0,0,0,0],[0,0,0,1,0,0,0],[0,0,0,0,1,0,0],[0,0,0,0,0,1,0],[0,0,0,0,0,0,1],
    [3,-1,-1,-1,0,0,0],[1,-1,0,0,-1,0,-1],[2,0,-1,0,-1,-1,0],[2,-1,-1,0,-1,0,0]])
print(p.adjacency_matrix())

[0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0]
[1 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1]
[0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0]
[1 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0]
[1 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0]
[0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0]
[0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
[0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0]
[1 1 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0]
[0 0 1 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 1]
[1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0]
[0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0]
[0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1]
[0 0 0 0 1 0 0 0 0 1 0 0 0 0

In [2]:
tabShape = [3,2,1]
maxEntry = len(tabShape) + 1
num = 0
stepCounts = [0]*(len(tabShape)*(maxEntry-1)+1)
for tab in SemistandardTableaux(tabShape, max_entry = maxEntry):
    tabList = setup(tab)
    F = WeakReversePlanePartition(tabList).hillman_grassl_inverse()
    if sumOfEntries(F) == 3:
        for row in F:
            print(row)
        print()
        stepCounts[sumOfEntries(F)] += 1
        num +=1
print(stepCounts)
print(num)
R.<t> = PolynomialRing(ZZ)
p = 0
for i in range(len(stepCounts)):
    p = p + stepCounts[i]*t^i
print(p)
print(p.factor())

(0, 0, 0)
(0, 2)
(1,)

(0, 0, 1)
(0, 1)
(1,)

(0, 0, 1)
(0, 2)
(0,)

(0, 0, 2)
(0, 0)
(1,)

(0, 0, 3)
(0, 0)
(0,)

(0, 0, 2)
(0, 1)
(0,)

(0, 0, 1)
(1, 1)
(0,)

(0, 0, 2)
(1, 0)
(0,)

(0, 1, 0)
(0, 1)
(1,)

(0, 1, 1)
(0, 0)
(1,)

(0, 1, 1)
(0, 1)
(0,)

(0, 1, 2)
(0, 0)
(0,)

(0, 1, 1)
(1, 0)
(0,)

(1, 0, 2)
(0, 0)
(0,)

(0, 2, 0)
(0, 0)
(1,)

(0, 2, 1)
(0, 0)
(0,)

(1, 1, 1)
(0, 0)
(0,)

(1, 0, 0)
(0, 2)
(0,)

(1, 0, 1)
(0, 1)
(0,)

(1, 1, 0)
(0, 1)
(0,)

[0, 0, 0, 20, 0, 0, 0, 0, 0, 0]
20
20*t^3
5 * 2^2 * t^3


In [5]:
n = 100
ans = [0]*(n+1)
ans[0] = 1
for k in range(1,n+1):
    for p in Partitions(k):
        currentMult = 1
        lastRow = p[0]
        good = True
        for i in range(1,len(p)):
            thisRow = p[i]
            if thisRow == lastRow:
                currentMult += 1
            elif lastRow - thisRow == currentMult:
                lastRow = thisRow
                currentMult = 1
            else:
                good = False
        if good and lastRow == currentMult:
            #print(p, k)
            ans[k] += 1
    print(k, ans[k])
print(ans)
runSum = 0
for x in ans:
    runSum += x
print(runSum)
R.<t> = PolynomialRing(ZZ)
p = 0
for i in range(len(ans)):
    p = p + ans[i]*t^i
print(p)
print(p.factor())

1 1
2 0
3 1
4 1
5 0
6 1
7 2
8 0
9 1
10 1
11 3
12 1
13 2
14 0
15 1
16 5
17 3
18 3
19 2
20 0
21 3
22 5
23 6
24 5
25 7
26 0
27 4
28 3
29 6
30 10
31 11
32 12
33 3
34 7
35 6
36 2
37 9
38 18
39 18
40 21
41 12
42 11
43 17
44 3
45 7
46 12
47 27
48 28
49 38
50 30
51 23
52 34
53 12
54 13
55 12
56 21
57 36
58 49
59 57
60 65
61 50
62 60
63 38


KeyboardInterrupt: 

In [26]:
n = 9
nprime = (n-1)/2
for k in range(1,n+1):
    kprime = (k-1)/2
    print(binomial(floor(nprime),floor(kprime))*binomial(ceil(nprime),ceil(kprime)))

1
4
16
24
36
24
16
4
1


In [4]:
m = 4
tabShape = [4,3,2,1]
maxEntry = len(tabShape) + 1
pos = posSet(tabShape)
neg = negSet(tabShape)
count = 0
num = 0
num2 = 0
for tab in SemistandardTableaux(tabShape, max_entry = maxEntry):
    count += 1
    if count % pow(10,6) == 0:
        print(count, num, num2)
    steps = 0
    tabList = setup(tab)
    for point in pos:
        i = point[0]
        j = point[1]
        steps += tabList[i][j]
    for point in neg:
        i = point[0]
        j = point[1]
        steps -= tabList[i][j]
    if steps == m*(m+1)/4:
        num += 1
        F = WeakReversePlanePartition(setup(tab)).hillman_grassl_inverse()
        good = True
        for i in range(len(F)):
            j = len(F[i]) - 1
            hookSum = 0
            for a in range(i):
                hookSum += F[a][j]
            for b in range(j):
                hookSum += F[i][b]
            hookSum += F[i][j]
            if F[i][j] != m - i - hookSum:
                good = False
                break
        if good:
            num2 += 1
            for row in F:
                print(row)
            print()
print(num2)

(0, 0, 0, 2)
(0, 1, 1)
(1, 0)
(0,)

(0, 0, 0, 2)
(1, 0, 1)
(0, 1)
(0,)

(0, 0, 2, 1)
(0, 1, 0)
(1, 0)
(0,)

(0, 0, 2, 1)
(1, 0, 0)
(0, 1)
(0,)

(0, 1, 1, 1)
(0, 0, 1)
(1, 0)
(0,)

(1, 0, 1, 1)
(0, 0, 1)
(0, 1)
(0,)

(1, 0, 1, 1)
(0, 2, 0)
(0, 0)
(0,)

(1, 1, 0, 1)
(0, 1, 1)
(0, 0)
(0,)

8


In [4]:
n = 7
tabShape = list()
for k in range(n,0,-1):
    tabShape.append(k)
minTab = list()
for x in tabShape:
    minTab.append([0]*x)
ans = set()
count = 0
num2 = 0
fDiagramBuilder(minTab, 0, 0, ans)
print("made em", len(ans))
for fDiag in ans:
    HGdiagram = WeakReversePlanePartition(fDiag)
    count += 1
    if count % pow(10,6) == 0:
        print(count, num2)
    good = True
    for i in range(len(HGdiagram)):
        j = len(HGdiagram[i]) - 1
        hookSum = 0
        for a in range(i):
            hookSum += HGdiagram[a][j]
        for b in range(j):
            hookSum += HGdiagram[i][b]
        hookSum += HGdiagram[i][j]
        if HGdiagram[i][j] != n - i - hookSum:
            good = False
            break
    if good:
        num2 += 1
print(count, num2)

KeyboardInterrupt: 

In [5]:
print(len(ans))

12547702


In [68]:
def superFDiagramBuilder(previous, maxTab, i, j):
    hookSum = 0
    for a in range(i):
        hookSum += previous[a][j]
    for b in range(j):
        hookSum += previous[i][b]
    col = j + 1
    maxPick = col - hookSum
    for k in range(maxPick + 1):
        tempNext = list()
        for a in range(len(previous)):
            tempRow = list()
            for b in range(len(previous[a])):
                tempRow.append(previous[a][b])
            tempNext.append(tempRow)
        tempNext[i][j] = k
        if isInBounds(previous, i, j+1):
            superFDiagramBuilder(tempNext, maxTab, i, j+1)
        else:
            if isInBounds(previous,i+1,0):
                superFDiagramBuilder(tempNext, maxTab, i+1, 0)
            else:
                temp = list()
                for m in range(len(tempNext)):
                    temp.append(tuple(tempNext[m]))
                check(temp)        
def check(temp):        
    global n
    if sumOfEntries(temp) == n*(n+1)/4:
        HGdiagram = WeakReversePlanePartition(temp)
        global count
        global num2
        count += 1
        if count % pow(10,6) == 0:
            print(count, num2)
        good = True
        for i in range(len(HGdiagram)):
            j = len(HGdiagram[i]) - 1
            hookSum = 0
            for a in range(i):
                hookSum += HGdiagram[a][j]
            for b in range(j):
                hookSum += HGdiagram[i][b]
            hookSum += HGdiagram[i][j]
            if HGdiagram[i][j] != n - i - hookSum:
                good = False
                break
        if good:
            tab = HGdiagram.hillman_grassl()
            if fitsIn(tab,maxTab):
                num2 += 1

In [69]:
n = 7
count = 0
num2 = 0
tabShape = list()
for k in range(n,0,-1):
    tabShape.append(k)
minTab = list()
maxTab = list()
for x in tabShape:
    minTab.append([0]*x)
for i in range(len(tabShape)):
    tempList = list()
    for j in range(1,tabShape[i] + 1):
        tempList.append(j)
    maxTab.append(tempList)
superFDiagramBuilder(minTab, maxTab, 0, 0)
print(count, num2)

1000000 0
2000000 0
3000000 466
4000000 748
5000000 756
6000000 1494
7000000 2026
8000000 2026
9000000 2374
10000000 2434
11000000 2726
12000000 3078
13000000 3512
14000000 3512
15000000 4095
16000000 4095
17000000 4523
18000000 4766
19000000 4960
20000000 5236
21000000 5458
22000000 5830
23000000 6190
24000000 6371
25000000 6720
26000000 7011
27000000 7276
28000000 7765
29000000 8003
30000000 8158
31000000 8420
32000000 8786
33000000 9096
34000000 9351
35000000 9687
36000000 9903
37000000 10308
38000000 10489
39000000 11007
40000000 11428
41000000 11577
42000000 11887
43000000 12577
44000000 12942
45000000 13611
46000000 14291
47000000 14892
48000000 15641
48873998 16550


In [67]:
print(count, num2)

212376 0


In [1]:
R.<t> = PolynomialRing(ZZ)
def matrixPoly(i,j,m):
    if j < 0:
        return 0
    elif j == 0:
        return 1
    else:
        p = 0
        for k in range(0,i+1):
            if j%(m+1) == 0:
                p += matrixPoly(i-k,j-1,m)
            else:
                p += t^(k)*matrixPoly(i-k,j-1,m)
        return p
def testPoly(i,j,m):
    q = 0
    for k in range(i+1):
        a = floor(j/(m+1))
        b = floor((m*j-1)/(m+1))
        q += t^k * binomial(i - k + a, i-k) * binomial(b+k,k)
    return q

In [29]:
m = 3
l = 4
R.<t> = PolynomialRing(ZZ)
for n in range(20):
    #something isn't right????
    #im so confused
    p = testPoly(n,m*n + (m+1)*l,m)
    for k in range(1, floor(m*n/(m+1))+ l +1):
        for i in range(k):
            p += (-1)^(i+1) * binomial(n + l - i, n + l - k) * binomial(n + l, n + l - i) * testPoly(n, m*n - (m+1)*k + (m+1) * l,m)
    if p == 0:
        print(p)
    else:
        print(p.factor())

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [23]:
m = 4
i = 6
for j in range(11):
    print(j,testPoly(i,j,m) -  testPoly(i,j-1,m))

0 1
1 t^6 + t^5 + t^4 + t^3 + t^2 + t
2 6*t^6 + 5*t^5 + 4*t^4 + 3*t^3 + 2*t^2 + t
3 21*t^6 + 15*t^5 + 10*t^4 + 6*t^3 + 3*t^2 + t
4 56*t^6 + 35*t^5 + 20*t^4 + 10*t^3 + 4*t^2 + t
5 56*t^5 + 70*t^4 + 60*t^3 + 40*t^2 + 20*t + 6
6 126*t^6 + 140*t^5 + 105*t^4 + 60*t^3 + 25*t^2 + 6*t
7 252*t^6 + 252*t^5 + 168*t^4 + 84*t^3 + 30*t^2 + 6*t
8 462*t^6 + 420*t^5 + 252*t^4 + 112*t^3 + 35*t^2 + 6*t
9 792*t^6 + 660*t^5 + 360*t^4 + 144*t^3 + 40*t^2 + 6*t
10 792*t^5 + 990*t^4 + 720*t^3 + 360*t^2 + 120*t + 21


In [52]:
#maxEntry implementation - checking HG of constrained parts of (staircases?) (hopefully general shapes later).
n = 4
tabShape = list()
innerTabShape = list()
tabShape.append(n)
for i in range(n-1,0,-1):
    tabShape.append(i)
    innerTabShape.append(i)
maxEntry = len(tabShape) + 1
pos = posSet(tabShape)
neg = negSet(tabShape)
innerPos = negSet(innerTabShape)
innerNeg = posSet(innerTabShape)
stepCounts = [0]*(len(tabShape)*(maxEntry-1)+1)
innerStepCounts = [0]*(len(tabShape)*(maxEntry-1)+1)
stepMatrix = [[0 for i in range(len(tabShape)*(maxEntry-1)+1)] for j in range(len(tabShape)*(maxEntry-1)+1)]
num = 0
for tab in SemistandardTableaux(tabShape, max_entry = maxEntry):
    steps = 0
    innerSteps = 0
    tabList = setup(tab)
    for point in pos:
        i = point[0]
        j = point[1]
        steps += tabList[i][j]
    for point in neg:
        i = point[0]
        j = point[1]
        steps -= tabList[i][j]
    stepCounts[steps] += 1 
    for point in innerNeg:
        i = point[0]
        j = point[1]
        innerSteps += tabList[i][j]
    for point in innerPos:
        i = point[0]
        j = point[1]
        innerSteps += tabList[i][j]
    innerStepCounts[innerSteps] += 1
    stepMatrix[innerSteps][steps + innerSteps] += 1
print(stepCounts)
print(innerStepCounts)
print()
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)
printableMatrix = np.array(stepMatrix)
print(printableMatrix)
# for row in stepMatrix:
#     print(row)
# runSum = 0
# for x in stepCounts:
#     runSum += x
# print(runSum)
# R.<t> = PolynomialRing(ZZ)
# p = 0
# for i in range(len(stepCounts)):
#     p = p + stepCounts[i]*t^i
# print(p)
# print(p.factor())
# q = 0
# for i in range(len(innerStepCounts)):
#     q = q + innerStepCounts[i]*t^i
# print(q)
# print(q.factor())

[1, 10, 45, 120, 210, 252, 210, 120, 45, 10, 1, 0, 0, 0, 0, 0, 0]
[120, 172, 158, 176, 142, 98, 82, 44, 20, 10, 2, 0, 0, 0, 0, 0, 0]

[[ 1  4  9 15 20 22 20 15  9  4  1  0  0  0  0  0  0]
 [ 0  0  3 11 22 32 36 32 22 11  3  0  0  0  0  0  0]
 [ 0  0  0  2 10 23 34 37 30 17  5  0  0  0  0  0  0]
 [ 0  0  0  0  1  8 23 38 43 35 19  7  2  0  0  0  0]
 [ 0  0  0  0  0  0  5 18 33 38 28 15  5  0  0  0  0]
 [ 0  0  0  0  0  0  0  1 10 23 27 22 11  3  1  0  0]
 [ 0  0  0  0  0  0  0  0  1  6 16 24 20 11  4  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  9 14 13  6  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  3  7  6  2  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  3  3  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [